apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::621721788004:role/shopcloud-eks-node
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::621721788004:role/gh-actions-shopcloud-dev
      username: gh-actions-shopcloud-dev
      groups:
      - system:masters
    - rolearn: arn:aws:iam::621721788004:role/gh-actions-shopcloud-prod
      username: gh-actions-shopcloud-prod
      groups:
      - system:masters
