# prod environment — composes the modules together.
# Run terraform from this directory: terraform init && terraform apply

terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region

  # Tags applied to every resource that supports them.
  default_tags {
    tags = {
      Project     = "shopcloud"
      Environment = "prod"
      ManagedBy   = "terraform"
    }
  }
}

# ----------------------------------------------------------------------------
# Network — VPC, subnets across 3 AZs, NAT gateway.
# Everything else lives inside this VPC.
# ----------------------------------------------------------------------------

module "network" {
  source = "../../modules/network"

  name     = "shopcloud"
  vpc_cidr = "10.0.0.0/16"
  azs      = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
}



# ----------------------------------------------------------------------------
# EKS — Kubernetes control plane + managed node group.
# Pods will run on the EC2 nodes this creates.
# ----------------------------------------------------------------------------
module "eks" {
  source = "../../modules/eks"

  name               = "shopcloud"
  kubernetes_version = "1.30"
  vpc_id             = module.network.vpc_id
  subnet_ids         = module.network.private_subnet_ids
}



# ----------------------------------------------------------------------------
# Data — RDS Postgres (Multi-AZ) and ElastiCache Redis.
# Both sit in private DB subnets, only reachable from the EKS nodes.
# ----------------------------------------------------------------------------
module "data" {
  source = "../../modules/data"

  name              = "shopcloud"
  vpc_id            = module.network.vpc_id
  db_subnet_ids     = module.network.database_subnet_ids
  redis_subnet_ids  = module.network.database_subnet_ids
  allowed_source_sg = module.eks.node_security_group_id

  db_username = "shopcloud"
  # Password is generated by the module and stored in Secrets Manager later.
  # For this first pass we accept it as a variable to keep things simple.
  db_password = var.db_password
}





# ----------------------------------------------------------------------------
# Storage — ECR repositories, one per service.
# CI pushes Docker images here; EKS pulls from here.
# ----------------------------------------------------------------------------
module "storage" {
  source = "../../modules/storage"

  services = ["catalog", "cart", "checkout", "auth", "admin", "admin-ui"]
}



# ============================================================================
# INVOICE PIPELINE
# checkout (pod) ──SQS──▶ invoice-generator (Lambda)
#                                ├── render PDF
#                                ├── upload to S3
#                                ├── send via SES
#                                └── update RDS
# ============================================================================

# Store the DB password in Secrets Manager so the Lambda can fetch it at runtime.
# EKS pods read it via the existing var.db_password mechanism for now.
resource "aws_secretsmanager_secret" "db_password" {
  name = "shopcloud/rds/password"
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = var.db_password
}

# ----------------------------------------------------------------------------
# S3 — invoices bucket
# ----------------------------------------------------------------------------
module "s3_invoices" {
  source = "../../modules/s3"

  # Bucket names are globally unique. Prepend account ID to avoid collisions.
  bucket_name = "shopcloud-invoices-${data.aws_caller_identity.current.account_id}"
}

data "aws_caller_identity" "current" {}

# ----------------------------------------------------------------------------
# SQS — invoice events queue + DLQ
# ----------------------------------------------------------------------------
module "messaging" {
  source = "../../modules/messaging"
  name   = "shopcloud"
}

# ----------------------------------------------------------------------------
# Lambda — invoice generator
# ----------------------------------------------------------------------------
module "lambda_invoice" {
  source = "../../modules/lambda"

  function_name         = "shopcloud-invoice-generator"
  vpc_id                = module.network.vpc_id
  subnet_ids            = module.network.private_subnet_ids
  rds_security_group_id = module.data.rds_security_group_id

  sqs_queue_arn  = module.messaging.queue_arn
  s3_bucket_name = module.s3_invoices.bucket_name
  s3_bucket_arn  = module.s3_invoices.bucket_arn

  ses_sender    = var.ses_sender
  db_secret_arn = aws_secretsmanager_secret.db_password.arn
  db_host       = module.data.rds_endpoint
  db_name       = module.data.rds_db_name
  db_user       = "shopcloud"
}

# ----------------------------------------------------------------------------
# IRSA — checkout pod can sqs:SendMessage to the invoice queue.
# Annotate the K8s service account with the role ARN this exports.
# ----------------------------------------------------------------------------
data "aws_iam_policy_document" "checkout_sqs" {
  statement {
    actions   = ["sqs:SendMessage", "sqs:GetQueueUrl"]
    resources = [module.messaging.queue_arn]
  }
}

module "irsa_checkout" {
  source = "../../modules/iam_irsa"

  role_name            = "shopcloud-checkout"
  namespace            = "prod"
  service_account_name = "checkout"
  oidc_provider_arn    = module.eks.oidc_provider_arn
  oidc_provider_url    = module.eks.oidc_provider_url
  policy_json          = data.aws_iam_policy_document.checkout_sqs.json
}
