# prod environment — composes the modules together.
# Run terraform from this directory: terraform init && terraform apply

terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region

  # Tags applied to every resource that supports them.
  default_tags {
    tags = {
      Project     = "shopcloud"
      Environment = "prod"
      ManagedBy   = "terraform"
    }
  }
}

# us-east-1 alias — required for:
#   - WAFv2 CLOUDFRONT-scoped Web ACLs (must live in us-east-1)
#   - Cross-region RDS read replica for DR
provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"

  default_tags {
    tags = {
      Project     = "shopcloud"
      Environment = "prod"
      ManagedBy   = "terraform"
    }
  }
}

# ----------------------------------------------------------------------------
# Network — VPC, subnets across 3 AZs, NAT gateway.
# Everything else lives inside this VPC.
# ----------------------------------------------------------------------------

module "network" {
  source = "../../modules/network"

  name     = "shopcloud"
  vpc_cidr = "10.0.0.0/16"
  azs      = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
}



# ----------------------------------------------------------------------------
# EKS — Kubernetes control plane + managed node group.
# Pods will run on the EC2 nodes this creates.
# ----------------------------------------------------------------------------
module "eks" {
  source = "../../modules/eks"

  name               = "shopcloud"
  kubernetes_version = "1.30"
  vpc_id             = module.network.vpc_id
  subnet_ids         = module.network.private_subnet_ids
}



# ----------------------------------------------------------------------------
# Data — RDS Postgres (Multi-AZ) and ElastiCache Redis.
# Both sit in private DB subnets, only reachable from the EKS nodes.
# ----------------------------------------------------------------------------
module "data" {
  source = "../../modules/data"

  name              = "shopcloud"
  vpc_id            = module.network.vpc_id
  db_subnet_ids     = module.network.database_subnet_ids
  redis_subnet_ids  = module.network.database_subnet_ids
  allowed_source_sg = module.eks.node_security_group_id

  db_username = "shopcloud"
  # Password is generated by the module and stored in Secrets Manager later.
  # For this first pass we accept it as a variable to keep things simple.
  db_password = var.db_password

  # We are running terraform from a laptop outside the VPC, so the postgres
  # provider cannot reach RDS to run CREATE DATABASE. Set false here and create
  # the per-env databases manually from a kubectl-exec'd pod inside the cluster
  # (see deployment.md, post-Step 4 cleanup).
  create_per_env_databases = false
}





# ----------------------------------------------------------------------------
# Storage — ECR repositories.
# Two images:
#   - shopcloud-app: the one Python image used by every backend Deployment.
#                    Each Deployment overrides the uvicorn entrypoint to pick
#                    a service (services.<name>.main:app).
#   - admin-ui:      static NGINX image for the admin console (separate because
#                    it ships HTML/JS, not the Python app).
# CI pushes Docker images here; EKS pulls from here.
# ----------------------------------------------------------------------------
module "storage" {
  source = "../../modules/storage"

  # invoice-worker is the KEDA-scaled in-cluster SQS consumer (mirror of the
  # Lambda) — it ships as its own image, see services/invoice_worker/Dockerfile.
  services = ["shopcloud-app", "admin-ui", "invoice-worker"]
}



# ============================================================================
# INVOICE PIPELINE
# checkout (pod) ──SQS──▶ invoice-generator (Lambda)
#                                ├── render PDF
#                                ├── upload to S3
#                                ├── send via SES
#                                └── update RDS
# ============================================================================

# Store the DB password in Secrets Manager so the Lambda can fetch it at runtime.
# EKS pods read it via the existing var.db_password mechanism for now.
resource "aws_secretsmanager_secret" "db_password" {
  name = "shopcloud/rds/password"
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = var.db_password
}

# ----------------------------------------------------------------------------
# S3 — invoices bucket
# ----------------------------------------------------------------------------
module "s3_invoices" {
  source = "../../modules/s3"

  # Bucket names are globally unique. Prepend account ID to avoid collisions.
  bucket_name = "shopcloud-invoices-${data.aws_caller_identity.current.account_id}"
}

data "aws_caller_identity" "current" {}

# ----------------------------------------------------------------------------
# SQS — invoice events queue + DLQ
# ----------------------------------------------------------------------------
module "messaging" {
  source = "../../modules/messaging"
  name   = "shopcloud"
}

# ----------------------------------------------------------------------------
# Lambda — invoice generator
# ----------------------------------------------------------------------------
module "lambda_invoice" {
  source = "../../modules/lambda"

  function_name         = "shopcloud-invoice-generator"
  vpc_id                = module.network.vpc_id
  subnet_ids            = module.network.private_subnet_ids
  rds_security_group_id = module.data.rds_security_group_id

  sqs_queue_arn  = module.messaging.queue_arn
  s3_bucket_name = module.s3_invoices.bucket_name
  s3_bucket_arn  = module.s3_invoices.bucket_arn

  ses_sender    = var.ses_sender
  db_secret_arn = aws_secretsmanager_secret.db_password.arn
  db_host       = module.data.rds_endpoint
  # The Lambda only consumes events published by prod checkout (dev never
  # publishes -- INVOICE_QUEUE_URL is empty in dev's overlay). Point it at
  # the prod-namespaced database where orders actually land. The master
  # `shopcloud` DB that data module exports has no schema -- using it here
  # caused 'relation "orders" does not exist' DLQ failures.
  db_name = "shopcloud_prod"
  db_user = "shopcloud"
}

# ----------------------------------------------------------------------------
# IRSA — checkout pod can sqs:SendMessage to the invoice queue.
# Annotate the K8s service account with the role ARN this exports.
# ----------------------------------------------------------------------------
data "aws_iam_policy_document" "checkout_sqs" {
  statement {
    actions   = ["sqs:SendMessage", "sqs:GetQueueUrl"]
    resources = [module.messaging.queue_arn]
  }
}

module "irsa_checkout" {
  source = "../../modules/iam_irsa"

  role_name            = "shopcloud-checkout"
  namespaces           = ["prod", "dev"] # one cluster, two namespaces share this role
  service_account_name = "checkout"
  oidc_provider_arn    = module.eks.oidc_provider_arn
  oidc_provider_url    = module.eks.oidc_provider_url
  policy_json          = data.aws_iam_policy_document.checkout_sqs.json
}

# ----------------------------------------------------------------------------
# IRSA — Cluster Autoscaler. The autoscaler Deployment in kube-system watches
# for Pending pods that don't fit on existing nodes and grows the EKS managed
# node group via the EC2 Auto Scaling API. Without this role, HPA can scale
# pods up to the point existing nodes are full and then stalls.
# ----------------------------------------------------------------------------
data "aws_iam_policy_document" "cluster_autoscaler" {
  statement {
    actions = [
      "autoscaling:DescribeAutoScalingGroups",
      "autoscaling:DescribeAutoScalingInstances",
      "autoscaling:DescribeLaunchConfigurations",
      "autoscaling:DescribeScalingActivities",
      "autoscaling:DescribeTags",
      "ec2:DescribeImages",
      "ec2:DescribeInstanceTypes",
      "ec2:DescribeLaunchTemplateVersions",
      "ec2:GetInstanceTypesFromInstanceRequirements",
      "eks:DescribeNodegroup",
    ]
    resources = ["*"]
  }

  # Mutating actions are scoped to ASGs tagged for this cluster.
  statement {
    actions = [
      "autoscaling:SetDesiredCapacity",
      "autoscaling:TerminateInstanceInAutoScalingGroup",
    ]
    resources = ["*"]
    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/k8s.io/cluster-autoscaler/${module.eks.cluster_name}"
      values   = ["owned"]
    }
  }
}

module "irsa_cluster_autoscaler" {
  source = "../../modules/iam_irsa"

  role_name            = "shopcloud-cluster-autoscaler"
  namespace            = "kube-system"
  service_account_name = "cluster-autoscaler"
  oidc_provider_arn    = module.eks.oidc_provider_arn
  oidc_provider_url    = module.eks.oidc_provider_url
  policy_json          = data.aws_iam_policy_document.cluster_autoscaler.json
}

# ----------------------------------------------------------------------------
# IRSA -- AWS Load Balancer Controller. The controller (a Deployment in
# kube-system installed via Helm by deploy.yml) watches Ingress and Service
# resources, and provisions ALBs/NLBs in AWS to expose them. Without this
# role, the controller can't call the elasticloadbalancing/ec2/iam APIs and
# every Ingress sits forever with an empty ADDRESS column.
#
# Policy is the AWS-published canonical policy for controller v2.7+
# (compatible with v2.8.x). Sourced from
# https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json
# and embedded as alb-controller-policy.json so apply does not depend on
# fetching at runtime.
# ----------------------------------------------------------------------------
module "irsa_alb_controller" {
  source = "../../modules/iam_irsa"

  role_name            = "shopcloud-alb-controller"
  namespace            = "kube-system"
  service_account_name = "aws-load-balancer-controller"
  oidc_provider_arn    = module.eks.oidc_provider_arn
  oidc_provider_url    = module.eks.oidc_provider_url
  policy_json          = file("${path.module}/alb-controller-policy.json")
}

# ----------------------------------------------------------------------------
# IRSA — invoice-worker pod (KEDA-scaled SQS consumer). Mirror of the Lambda
# permissions: receive/delete from the invoice queue, write to the invoice
# bucket, send via SES, read the DB password from Secrets Manager. Same
# ServiceAccount name (invoice-worker) as in keda-invoice-scaler.yaml.
# ----------------------------------------------------------------------------
data "aws_iam_policy_document" "invoice_worker" {
  statement {
    sid    = "ConsumeQueue"
    actions = [
      "sqs:ReceiveMessage",
      "sqs:DeleteMessage",
      "sqs:GetQueueAttributes",
      "sqs:ChangeMessageVisibility",
      "sqs:GetQueueUrl",
    ]
    resources = [module.messaging.queue_arn]
  }

  statement {
    sid       = "WriteInvoices"
    actions   = ["s3:PutObject", "s3:PutObjectAcl", "s3:GetObject"]
    resources = ["${module.s3_invoices.bucket_arn}/*"]
  }

  statement {
    sid       = "SendEmail"
    actions   = ["ses:SendEmail", "ses:SendRawEmail"]
    resources = ["*"]
  }

  statement {
    sid       = "ReadDbSecret"
    actions   = ["secretsmanager:GetSecretValue"]
    resources = [aws_secretsmanager_secret.db_password.arn]
  }
}

module "irsa_invoice_worker" {
  source = "../../modules/iam_irsa"

  role_name            = "shopcloud-invoice-worker"
  namespaces           = ["prod", "dev"]
  service_account_name = "invoice-worker"
  oidc_provider_arn    = module.eks.oidc_provider_arn
  oidc_provider_url    = module.eks.oidc_provider_url
  policy_json          = data.aws_iam_policy_document.invoice_worker.json
}

# ============================================================================
# IDENTITY — Cognito user pools (customers + admins)
# ============================================================================
module "cognito" {
  source = "../../modules/cognito"
  name   = "shopcloud"

  # Cognito's Hosted UI strictly checks redirect_uri against this allow-list.
  # The storefront constructs its redirect from `location.origin + pathname`
  # (see frontend/cognito.js), so the URL we register must match exactly.
  #
  # Wired from module.edge so any change to the CloudFront domain (e.g.
  # adding a custom domain later) updates Cognito automatically. Falls back
  # to the placeholder defaults when edge is not yet provisioned (Step 8
  # not done yet).
  # Both prod and dev CloudFront URLs end up in the customer pool's allow-list
  # so users can sign in from either. Single Cognito pool across envs is
  # intentional -- it lets a user signed up via dev also sign in via prod
  # (helpful for demos, harmless because the cluster is shared anyway).
  customer_callback_urls = length(module.edge) > 0 ? flatten([
    for env, edge in module.edge : [
      "https://${edge.cloudfront_domain_name}/",
      "https://${edge.cloudfront_domain_name}/callback",
    ]
  ]) : ["https://shopcloud.local/callback"]

  customer_logout_urls = length(module.edge) > 0 ? [
    for env, edge in module.edge : "https://${edge.cloudfront_domain_name}/"
  ] : ["https://shopcloud.local/"]

  # Admin callback URLs cover both the VPN-reachable internal ALB hostname
  # (when admins connect via Client VPN) and localhost (when admins
  # port-forward via kubectl for break-glass access).
  #
  # The internal ALB DNS is currently hardcoded -- it changes if the ALB
  # is replaced. For real prod, swap to a stable Route53 alias in a
  # private hosted zone (e.g. admin.internal.shopcloud) and reference that
  # via a Terraform output.
  admin_callback_urls = [
    "https://internal-k8s-prod-shopclou-912c413a33-1214551243.eu-west-1.elb.amazonaws.com/",
    "https://internal-k8s-prod-shopclou-912c413a33-1214551243.eu-west-1.elb.amazonaws.com/callback",
    "https://localhost/",
    "https://localhost/callback",
  ]
  admin_logout_urls = [
    "https://internal-k8s-prod-shopclou-912c413a33-1214551243.eu-west-1.elb.amazonaws.com/",
    "https://localhost/",
  ]
}

# ============================================================================
# STOREFRONT + EDGE -- one CloudFront distribution + one S3 storefront bucket
# per environment, keyed by env name (prod, dev). Each environment gets its
# own URL backed by its own ALB:
#
#   <prod cloudfront>.cloudfront.net  -> prod ALB -> prod namespace pods
#   <dev cloudfront>.cloudfront.net   -> dev  ALB -> dev  namespace pods
#
# Wiring:
#   - `var.public_alb_dns_names` is a map(env -> ALB DNS); one CloudFront +
#     bucket per non-empty entry.
#   - `var.frontend_origin_enabled` is a map(env -> bool) that controls
#     whether CloudFront wires the S3 bucket as an origin (the two-pass
#     dance, see variables.tf).
#
# State migration note: the original code shipped a single `module.edge[0]`
# and `module.s3_frontend[0]`. To keep the existing CloudFront/bucket alive
# under their new addresses, run before the next plan:
#   terraform state mv 'module.edge[0]'        'module.edge["dev"]'
#   terraform state mv 'module.s3_frontend[0]' 'module.s3_frontend["dev"]'
# (the existing CloudFront points at the dev ALB; renaming preserves it).
# ============================================================================
module "s3_frontend" {
  for_each = { for env, dns in var.public_alb_dns_names : env => dns if dns != "" }
  source   = "../../modules/s3_frontend"

  # The "dev" entry must keep the original bucket name -- bucket names are
  # immutable and we are state-mv-ing the existing resource into ["dev"].
  # New environments get a name suffixed with the env to disambiguate.
  bucket_name = each.key == "dev" ? (
    "shopcloud-frontend-${data.aws_caller_identity.current.account_id}"
    ) : (
    "shopcloud-frontend-${each.key}-${data.aws_caller_identity.current.account_id}"
  )

  # cloudfront_distribution_arn is deprecated/ignored -- the bucket policy
  # now scopes by AWS account ID, breaking the edge<->s3_frontend cycle.
  # Field omitted (defaults to "").
}

module "edge" {
  for_each = { for env, dns in var.public_alb_dns_names : env => dns if dns != "" }
  source   = "../../modules/edge"
  providers = {
    aws           = aws
    aws.us_east_1 = aws.us_east_1
  }

  name             = "shopcloud-${each.key}"
  alb_dns_name     = each.value
  hosted_zone_id   = var.hosted_zone_id
  domain_name      = var.domain_name
  primary_region   = var.region
  secondary_region = "us-east-1"

  # Per-env two-pass: lookup with a `false` default keeps newly-added envs
  # in pass-1 mode automatically. Flip to true in tfvars after pass 1 has
  # applied for that env.
  frontend_bucket_regional_domain_name = lookup(var.frontend_origin_enabled, each.key, false) ? module.s3_frontend[each.key].bucket_regional_domain_name : ""
}

# ============================================================================
# DR — Cross-region RDS read replica in us-east-1
# Promoted manually if eu-west-1 has a regional outage.
# ============================================================================
resource "aws_db_instance" "replica_us_east_1" {
  count    = var.enable_cross_region_replica ? 1 : 0
  provider = aws.us_east_1

  identifier          = "shopcloud-postgres-replica"
  replicate_source_db = module.data.rds_arn
  instance_class      = "db.t3.micro"

  publicly_accessible = false
  skip_final_snapshot = true

  tags = { Name = "shopcloud-postgres-replica" }
}

# ============================================================================
# ADMIN PATH — Client VPN (cert-based, MFA via the admin Cognito pool)
# Server + client root certs must be uploaded to ACM out-of-band.
# ============================================================================
module "vpn" {
  count  = var.enable_client_vpn ? 1 : 0
  source = "../../modules/vpn"

  name     = "shopcloud"
  vpc_id   = module.network.vpc_id
  vpc_cidr = "10.0.0.0/16"

  # Each subnet association costs ~$0.10/hr (~$72/mo) regardless of usage.
  # Single-AZ is fine for occasional admin access in a learning project.
  # For real prod, expand this to all 3 private_subnet_ids -- ~$216/mo for
  # multi-AZ availability so a single-AZ outage cannot lock admins out.
  subnet_ids = slice(module.network.private_subnet_ids, 0, 1)

  acm_server_cert_arn      = var.vpn_server_cert_arn
  acm_client_root_cert_arn = var.vpn_client_root_cert_arn
  # When set, enforces SAML+MFA on top of the client cert. Leave empty for
  # cert-only (dev). The diagram requires cert+MFA for production.
  saml_provider_arn = var.vpn_saml_provider_arn
}
